#!/usr/bin/env python3
"""Generate index_en.html from index_4.html with English UI text."""
import re
from pathlib import Path

src = Path("/Users/wangyongcai/Downloads/index_4.html")
dst = Path("/Users/wangyongcai/Downloads/index_en.html")
html = src.read_text(encoding="utf-8")

PROFILE_BIO_EN = """<div class="profile-bio-wrap">
<p class="profile-bio-lead">Yongcai Wang is a Professor and Ph.D. advisor in the Department of Computer Science, Renmin University of China. He serves as Deputy Chair of the Computer Science Department and Director of the Research and Discipline Construction Committee at the School of Information. He received his B.S. and Ph.D. from the Department of Automation, Tsinghua University. <strong>His research spans multi-agent systems, computer vision, Spatial AI, collaborative perception, and multi-agent reinforcement learning</strong>, with 120+ publications in leading journals and conferences, including 70+ CCF Class-A/B papers. His work has been applied to intelligent vehicles, unmanned vessels, and visual object detection and localization.</p>
<details class="profile-bio-details">
<summary>More on projects, awards &amp; academic service</summary>
<div class="profile-bio-more">
<p>He has led multiple National Natural Science Foundation of China projects, sub-projects under national S&amp;T support programs, and industry collaborations. Awards include a First Prize for Technical Invention from the China Institute of Navigation (2021) for maritime target localization, a Second Prize for Scientific and Technological Progress (2022), a Ministry of Transport Major Innovation Achievement award, and a Third Prize in Petroleum and Chemical Automation Science and Technology (2026).</p>
<p>He serves as an executive member of CCF technical committees on intelligent robots and IoT, an executive member of the DEDS committee of the Chinese Association of Automation, SIGBED China, and CAAI committees on cognition and information processing; as a PC member for CIKM 2025, WWW 2025, AAAI 2026, and others; and on the editorial boards of <em>Computer Science and Technology</em> and the <em>International Journal of Robotics and Automation Technology</em>.</p>
</div>
</details>
</div>"""

def sub(pairs):
    global html
    for a, b in pairs:
        html = html.replace(a, b)

sub([
    ('<html lang="zh-CN">', '<html lang="en">'),
    ('<title>王永才 — 中国人民大学计算机系</title>', '<title>Yongcai Wang — Renmin University of China</title>'),
    ("family=Noto+Serif+SC:wght@400;600;700&amp;family=Noto+Sans+SC:wght@300;400;500",
     "family=Noto+Serif:wght@400;600;700&amp;family=Noto+Sans:wght@300;400;500;600"),
    ("font-family: 'Noto Sans SC', sans-serif;", "font-family: 'Noto Sans', sans-serif;"),
    ("font-family: 'Noto Serif SC', serif;", "font-family: 'Noto Serif', serif;"),
    ('alt="王永才"', 'alt="Yongcai Wang"'),
    ('<motion.div class="sidebar-name">王永才</motion.div>', '<div class="sidebar-name">Yongcai Wang</div>'),
    ('<motion.div class="sidebar-name">王永才</div>', '<div class="sidebar-name">Yongcai Wang</div>'),
    ('<div class="sidebar-name">王永才</div>', '<div class="sidebar-name">Yongcai Wang</div>'),
    ('<div class="sidebar-title">教授 · 博士生导师<br/>计算机系副系主任</motion.div>',
     '<div class="sidebar-title">Professor · Ph.D. Advisor<br/>Deputy Chair, Dept. of Computer Science</div>'),
    ('<div class="sidebar-title">教授 · 博士生导师<br/>计算机系副系主任</div>',
     '<div class="sidebar-title">Professor · Ph.D. Advisor<br/>Deputy Chair, Dept. of Computer Science</div>'),
    ('<div class="sidebar-inst">中国人民大学信息学院</div>', '<div class="sidebar-inst">School of Information, RUC</div>'),
    ('<div class="nav-section-label">个人信息</div>', '<div class="nav-section-label">Profile</div>'),
    ('<a href="#profile"><span class="nav-icon">◎</span> 个人简介</a>', '<a href="#profile"><span class="nav-icon">◎</span> About</a>'),
    ('<a href="#research"><span class="nav-icon">◈</span> 研究方向</a>', '<a href="#research"><span class="nav-icon">◈</span> Research</a>'),
    ('<a href="#recruit"><span class="nav-icon">✦</span> 招生信息</a>', '<a href="#recruit"><span class="nav-icon">✦</span> Prospective Students</a>'),
    ('<div class="nav-section-label">学术动态</div>', '<div class="nav-section-label">News &amp; Talks</div>'),
    ('<a href="#news"><span class="nav-icon">⚡</span> 新闻动态</a>', '<a href="#news"><span class="nav-icon">⚡</span> News</a>'),
    ('<a href="#reports"><span class="nav-icon">◉</span> 近期报告</a>', '<a href="#reports"><span class="nav-icon">◉</span> Recent Talks</a>'),
    ('<div class="nav-section-label">教学科研</div>', '<div class="nav-section-label">Teaching &amp; Research</div>'),
    ('<a href="#teaching"><span class="nav-icon">◧</span> 教学</a>', '<a href="#teaching"><span class="nav-icon">◧</span> Teaching</a>'),
    ('<a href="#papers"><span class="nav-icon">◆</span> 代表性论文</a>', '<a href="#papers"><span class="nav-icon">◆</span> Selected Publications</a>'),
    ('<a href="#projects"><span class="nav-icon">◈</span> 科研项目</a>', '<a href="#projects"><span class="nav-icon">◈</span> Research Projects</a>'),
    ('<div class="nav-section-label">服务与荣誉</div>', '<div class="nav-section-label">Service &amp; Honors</div>'),
    ('<a href="#service"><span class="nav-icon">◐</span> 学术服务</a>', '<a href="#service"><span class="nav-icon">◐</span> Academic Service</a>'),
    ('<a href="#society"><span class="nav-icon">◑</span> 学会任职</a>', '<a href="#society"><span class="nav-icon">◑</span> Professional Societies</a>'),
    ('<a href="#awards"><span class="nav-icon">★</span> 获奖</a>', '<a href="#awards"><span class="nav-icon">★</span> Awards</a>'),
    ('<div class="nav-section-label">其他</div>', '<div class="nav-section-label">More</div>'),
    ('<a href="#background"><span class="nav-icon">◎</span> 教育和工作背景</a>', '<a href="#background"><span class="nav-icon">◎</span> Education &amp; Experience</a>'),
    ('<a href="#hobbies"><span class="nav-icon">◌</span> 闲暇爱好</a>', '<a href="#hobbies"><span class="nav-icon">◌</span> Hobbies</a>'),
    ('<a href="https://dblp.org/pid/04/2124.html" target="_blank">DBLP 论文目录 ↗</a><br/>\n<a href="index_en.html">English Version ↗</a>',
     '<a href="https://dblp.org/pid/04/2124.html" target="_blank">DBLP ↗</a><br/>\n<a href="index.html">Chinese Version ↗</a>'),
    ('alt="人大"', 'alt="RUC"'),
    ('alt="信息学院"', 'alt="School of Information"'),
    ('alt="计算机系"', 'alt="Dept. of Computer Science"'),
    ('<h2>主要研究方向</h2>', '<h2>Research Areas</h2>'),
    ('<span class="research-tag">智能体系统</span>', '<span class="research-tag">Multi-Agent Systems</span>'),
    ('<span class="research-tag">协同感知</span>', '<span class="research-tag">Collaborative Perception</span>'),
    ('<span class="research-tag">多智能体强化学习</span>', '<span class="research-tag">Multi-Agent RL</span>'),
    ('<h2>招生信息</h2>', '<h2>Prospective Students</h2>'),
    ('<strong>招生类型：</strong>', '<strong>Student types:</strong>'),
    ('<strong>期望要求：</strong>', '<strong>Requirements:</strong>'),
    ('<strong>加分项目：</strong>', '<strong>Preferred:</strong>'),
    ('<strong>联系方式：</strong>', '<strong>Contact:</strong>'),
    ('科研早培本科生、学硕、专硕、直博、普博、工程博士',
     "research-track undergraduates, academic/professional master's students, direct-entry Ph.D., general Ph.D., and engineering Ph.D. candidates"),
    ('学习能力强，英文听说读写能力好，编程能力强，自驱力强，对上述方向感兴趣，善于独立思考。',
     'Strong learning ability; proficient English; solid programming skills; self-driven; keen interest in the areas above; able to think independently.'),
    ('有科研论文发表、投稿、或重要比赛获奖经历的优先。',
     'Candidates with publications, submissions, or major competition awards are especially welcome.'),
    ('欢迎发送简历或自我介绍到 <a href="mailto:ycw@ruc.edu.cn">ycw@ruc.edu.cn</a>，欢迎联系。',
     'Please send your CV or a brief self-introduction to <a href="mailto:ycw@ruc.edu.cn">ycw@ruc.edu.cn</a>.'),
    ('<h2>新闻动态</h2>', '<h2>News</h2>'),
    ('<summary>▼ 展开早期动态</summary>', '<summary>▼ Earlier news</summary>'),
    ('被 ACM Multimedia 2024 <strong>Oral 3.97%</strong> 录用', 'accepted as ACM Multimedia 2024 <strong>Oral (3.97%)</strong>'),
    ('<h2>近期报告</h2>', '<h2>Recent Talks</h2>'),
    ('具身导航与三维重建的发展与交叉', 'Embodied Navigation and 3D Reconstruction: Developments and Synergies'),
    ('3D视觉 SLAM 技术前沿与进展', 'Frontiers and Advances in 3D Visual SLAM'),
    ('智能航运感知数据集整理', 'Intelligent Maritime Perception Datasets: A Survey'),
    ('多智能体协同感知研究进展', 'Advances in Multi-Agent Collaborative Perception'),
    ('视觉里程计从图优化到深度学习优化的发展', 'Visual Odometry: From Graph Optimization to Deep Learning'),
    ('WISE2026 · 澳门科技大学', 'WISE 2026 · MUST'),
    ('CWSN2025 · 低空经济论坛', 'CWSN 2025 · Low-Altitude Economy Forum'),
    ('2024人工智能与自主式交通国际学术会议', '2024 Intl. Conf. on AI and Autonomous Transportation'),
    ('中国人民大学计算机系第十届学术节', 'RUC CS Academic Festival (10th)'),
    ('中国自动化学会DEDS专委会', 'CAA DEDS Technical Committee'),
    ('<h2>教学</h2>', '<h2>Teaching</h2>'),
    ('《机器感知》', 'Machine Perception'),
    ('研究生专业课 · 2019—至今', 'Graduate course · 2019—present'),
    ('飞书共享文档：课程资料、习题等 ↗', 'Feishu wiki: materials &amp; assignments ↗'),
    ('《算法设计与分析II荣誉课程》', 'Algorithm Design and Analysis II (Honors)'),
    ('本科生必修课 · 2021—至今', 'Undergraduate required course · 2021—present'),
    ('《运筹学建模与算法》', 'Operations Research: Modeling and Algorithms'),
    ('课程主页 ↗', 'Course homepage ↗'),
    ('《图优化与Graph SLAM》', 'Graph Optimization and Graph SLAM'),
    ('短期课程', 'Short course'),
    ('《普适计算》', 'Ubiquitous Computing'),
    ('<h2>代表性论文</h2>', '<h2>Selected Publications</h2>'),
    ('<motion.div class="year-label">2021 and Before</motion.div>', '<motion.div class="year-label">2021 &amp; Earlier</motion.div>'),
    ('<div class="year-label">2021 and Before</div>', '<div class="year-label">2021 &amp; Earlier</div>'),
    ('<span class="paper-venue-tag ccfa">软件学报</span>', '<span class="paper-venue-tag ccfa">JoSW</span>'),
    ('<span class="paper-venue-tag ccfa">自动化学报</span>', '<span class="paper-venue-tag ccfa">ACTA</span>'),
    ('<h2>科研项目</h2>', '<h2>Research Projects</h2>'),
    ('《道路病害检测与三维量算技术开发项目》', 'Road Defect Detection and 3D Measurement'),
    ('《基于复杂环境下的全域感知算法开发》', 'Omni-Perception Algorithms in Complex Environments'),
    ('《基于数据-模型驱动的任务规划模型及优化算法》', 'Data–Model-Driven Task Planning and Optimization'),
    ('《能源系统智能算法研发》', 'Intelligent Algorithms for Energy Systems'),
    ('《无人集群数字孪生系统鲁棒性测试服务》', 'Robustness Testing for UAV Swarm Digital Twins'),
    ('《动态复杂场景下移动机器人环境定位感知研究》', 'Localization and Perception for Mobile Robots in Dynamic Scenes'),
    ('《高精点云地图构建与视觉定位导航方法研究》', 'High-Precision Point-Cloud Mapping and Visual Localization'),
    ('《基于视觉的机场飞鸟检测系统》', 'Vision-Based Airport Bird Detection'),
    ('《基于模块拼接的群智SLAM关键问题研究》', 'Modular Crowdsourced SLAM (Key Problems)'),
    ('《无人智能船的辅助驾驶决策系统》', 'Assisted Navigation for Unmanned Smart Vessels'),
    ('《紧耦合多源同步定位与地图构建的融合优化关键问题研究》', 'Tightly Coupled Multi-Sensor SLAM Fusion'),
    ('《国家科技支撑计划课题》', 'National S&amp;T Support Program Sub-Project'),
    ('《稀疏多元传感器网络跟踪用电设备状态的序列解码与部署优化关键问题研究》', 'Sparse Sensor Networks for Appliance State Tracking'),
    ('《基于序优化的大规模无线定位与自标定方法研究》', 'Large-Scale Wireless Localization via Ordinal Optimization'),
    ('项目负责人', 'PI'),
    ('国家自然科学基金 No.', 'NSFC No.'),
    ('国家自然科学青年基金 No.', 'NSFC Youth No.'),
    ('教育部博士点基金 No.', 'MOE Doctoral Fund No.'),
    ('<h2>学术服务</h2>', '<h2>Academic Service</h2>'),
    ('<strong>期刊编委</strong>：', '<strong>Editorial boards:</strong> '),
    ('程序委员会委员', 'PC member'),
    ('技术程序委员会 <strong>联合主席</strong>', 'TPC <strong>co-chair</strong>'),
    ('<strong>副主编</strong>', '<strong>associate editor</strong>'),
    ('<strong>论坛主席</strong>', '<strong>forum chair</strong>'),
    ('（宣传主席）', '(publicity chair)'),
    ('<strong>审稿人</strong>', '<strong>reviewer</strong>'),
    ('Valse2023《机器人具身智能》', 'VALSE 2023 Embodied Intelligence Forum'),
    ('等 CCF A 类会议；TON, TMC 等 CCF A 类期刊', 'and other CCF Class-A venues; TON, TMC, and other CCF Class-A journals'),
    ('<h2>学会任职</h2>', '<h2>Professional Societies</h2>'),
    ('中国计算机学会智能机器人专委会委员', 'CCF Technical Committee on Intelligent Robotics (member)'),
    ('中国计算机学会物联网专委会执行委员', 'CCF Technical Committee on IoT (executive member)'),
    ('中国控制学会会员 DEDS 专委会委员', 'CAA DEDS Technical Committee (member)'),
    ('中国人工智能学会青年工作委员会委员', 'CAAI Youth Working Committee (member)'),
    ('CAAI 认知系统与信息处理专委会委员', 'CAAI Cognitive Systems and Information Processing TC (member)'),
    ('CAAI 智能信息网络专委会委员', 'CAAI Intelligent Information Networks TC (member)'),
    ('青科委—智能无人交通系统专委会委员', 'Youth Committee — Intelligent Unmanned Transportation TC (member)'),
    ('<h2>获奖</h2>', '<h2>Awards</h2>'),
    ('中国人民大学优秀毕业生指导教师', 'Outstanding Graduate Advisor, RUC'),
    ('中国人民大学信息学院优秀教职工党员', 'Outstanding Faculty Party Member, RUC School of Information'),
    ('中国人民大学信息学院科研先进个人', 'Research Excellence Award, RUC School of Information'),
    ('中国航海学会科学技术进步二等奖', 'Second Prize, Science &amp; Technology Progress, China Institute of Navigation'),
    ('中国航海学会技术发明<strong>一等奖</strong>', 'First Prize, Technical Invention, China Institute of Navigation'),
    ('交通部中国交通运输重大科技创新成果（编号 2020LW043）', 'Major Transport Innovation Achievement (No. 2020LW043), MOT'),
    ('全国人工智能教学实践案例大赛二等奖', 'Second Prize, National AI Teaching Practice Case Competition'),
    ('中国人民大学十佳班主任', 'Top Ten Class Advisor, RUC'),
    ('中国人民大学优秀硕士毕业生指导教师', "Outstanding Master's Graduate Advisor, RUC"),
    ('中国人民大学本科教学优秀奖', 'Undergraduate Teaching Excellence Award, RUC'),
    ('最佳会议报告奖', 'Best Presentation Award'),
    ('最佳论文奖', 'Best Paper Award'),
    ('国际普适计算与通信大会最佳论文奖', 'Best Paper Award, Ubiquitous Computing and Communications Conference'),
    ('<h2>教育和工作背景</h2>', '<h2>Education &amp; Experience</h2>'),
    ('<span class="bg-role">本科</span>', '<span class="bg-role">B.S.</span>'),
    ('<span class="bg-role">直博</span>', '<span class="bg-role">Ph.D.</span>'),
    ('<span class="bg-role">副研究员</span>', '<span class="bg-role">Associate Researcher</span>'),
    ('<span class="bg-role">博士后 / 助理研究员</span>', '<span class="bg-role">Postdoc / Assistant Researcher</span>'),
    ('<span class="bg-role">访问学者</span>', '<span class="bg-role">Visiting Scholar</span>'),
    ('<span class="bg-role">教授（现任）</span>', '<span class="bg-role">Professor (current)</span>'),
    ('>清华大学自动化系</a>', '>Dept. of Automation, Tsinghua University</a>'),
    ('>NEC 中国研究院</a>', '>NEC Labs China</a>'),
    ('>清华大学交叉信息研究院</a>', '>IIIS, Tsinghua University</a>'),
    ('>美国康奈尔大学</a>', '>Cornell University</a>'),
    ('>中国人民大学信息学院</a>', '>School of Information, RUC</a>'),
    ('<h2>闲暇爱好</h2>', '<h2>Hobbies</h2>'),
    ('🏔️ 爬山', '🏔️ Hiking'),
    ('🏸 羽毛球', '🏸 Badminton'),
    ('🏃 跑步', '🏃 Running'),
    ('🍳 做美食', '🍳 Cooking'),
])

html = re.sub(
    r'<div class="profile-bio-wrap">[\s\S]*?</details>\s*</div>',
    PROFILE_BIO_EN,
    html,
    count=1,
)

dst.write_text(html, encoding='utf-8')
print('Wrote', dst)
